# Generated by Django 2.2.3 on 2019-12-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_quiz',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
