# Generated by Django 2.2.3 on 2020-01-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_quiz',
        ),
    ]
