# Generated by Django 2.2.3 on 2019-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.BooleanField(),
        ),
    ]
