# Generated by Django 2.2.3 on 2019-12-30 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191229_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_answered',
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
