# Generated by Django 2.2.3 on 2019-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190826_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
