# Generated by Django 2.2.3 on 2019-11-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190826_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_point', models.FloatField()),
                ('term', models.TextField()),
                ('definition', models.TextField()),
            ],
        ),
    ]
