# Generated by Django 2.2.3 on 2019-11-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_definition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Definition',
            new_name='Term',
        ),
    ]
