# Generated by Django 2.2.3 on 2019-12-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191230_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answered_on',
            new_name='date_answered',
        ),
    ]
