# Generated by Django 2.2.3 on 2019-12-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191230_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='date_answered',
            new_name='answered_on',
        ),
    ]
