# Generated by Django 2.2.3 on 2019-12-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191230_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='specification_range',
            new_name='spec_range',
        ),
    ]
