# Generated by Django 2.2.3 on 2019-12-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191230_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='spec_range',
            new_name='specification_range',
        ),
    ]
