# Generated by Django 2.2.3 on 2019-12-31 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20191230_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='completed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
