# Generated by Django 2.2.3 on 2019-12-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_quizresult_completed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_number', models.IntegerField()),
                ('topic_name', models.TextField()),
            ],
        ),
    ]
