# Generated by Django 2.2.3 on 2020-01-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecReference',
        ),
    ]
