# Generated by Django 2.2.3 on 2020-01-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_specreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.TextField(default='Quiz'),
            preserve_default=False,
        ),
    ]
