# Generated by Django 2.2.3 on 2020-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_quiz_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='diagram_name',
            field=models.FileField(upload_to=''),
        ),
    ]
