# Generated by Django 2.2.3 on 2020-01-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200104_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='diagram',
        ),
        migrations.AddField(
            model_name='question',
            name='diagram_name',
            field=models.TextField(default='nan'),
        ),
    ]
